"""add customer landmark

Revision ID: 479e8626518b
Revises: 9a5e437e5c9c
Create Date: 2026-09-12 19:33:01.652685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479e8626518b'
down_revision: Union[str, None] = '9a5e437e5c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('landmark', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'landmark')
    # ### end Alembic commands ###
